base_dir: "~/AIMED"

datasets:
  base: "${base_dir}/VLM_Seminar25_Dataset"
  chest: "${datasets.base}/chest_xrays"
  brain: "${datasets.base}/nova_brain"

chest:
  img_dir: "${datasets.chest}/images"
  annotations: "${datasets.chest}/annotations_len_50.json"
  model: "microsoft/maira-2"

brain:
  img_dir: "${datasets.brain_mri}/images"
  annotations: "${datasets.brain_mri}/annotations.json"
  model: "unet"

out_dir: "${base_dir}/output"

